disableHugoGeneratorInject = true

baseURL = 'https://localhost/'
languageCode = 'en-US'
title = 'Astral Linux'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Documentation'
pageRef = '/docs'
weight = 2
